//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderSystem.Database
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "Please Enter Product Name")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Please Enter Product Price")]
        public decimal ProductPrice { get; set; }
        [Required(ErrorMessage = "Please Enter Product Description")]
        public string ProductDescription { get; set; }
        [Required(ErrorMessage = "Please Select Product Picture")]
        public string ProductPicture { get; set; }
        public int RestoID { get; set; }
        [Required(ErrorMessage = "Please Select Product Discount")]
        public decimal Discount { get; set; }
    
        public virtual Restorent Restorent { get; set; }
    }
}
